disable swagger-validate action temporarily (#37)
Due to persistent error in the workflow we'd disable this workflow
temporarily and return success even on validation issue

```
Error: Error while validating in Swagger Editor
Error: TimeoutError: Waiting for selector `.info .main .title` failed: Waiting failed: 10000ms exceeded
Error: Process completed with exit code 1.
```